from tkinter import *
from tkcalendar import *
import pymysql
from tkinter import ttk, messagebox, Radiobutton

frame = Tk()
frame.title("Plate forme de l'hôpital")
frame.geometry("1080x720")
frame.maxsize(width=1020 ,  height=800)


heading = Label(frame, text = "Enregistrement de nouveau né" , font = 'Verdana 20 bold')
heading.pack()


first_name = Label(frame, text= "Nom :" , font='Verdana 14 bold')
first_name.place(x=80,y=130)
#first_name.pack()
last_name = Label(frame, text= "Prénom :" , font='Verdana 14 bold')
last_name.place(x=80,y=160)
#last_name.pack()
datenaiss = Label(frame, text= "Date de naissance :" , font='Verdana 14 bold')
datenaiss.place(x=80,y=190)
#datenaiss.pack()
Gender = Label(frame, text= "Sexe :" , font='Verdana 14 bold')
Gender.place(x=80,y=220)
#Gender.pack()
city = Label(frame, text= "Ville de naissance :" , font='Verdana 14 bold')
city.place(x=80,y=250)
#city.pack()
dadname = Label(frame, text= "Nom du père :" , font='Verdana 14 bold')
dadname.place(x=80,y=280)
#dadname.pack()
dadsituation = Label(frame, text= "Situation matrimoniale :" , font='Verdana 14 bold')
dadsituation.place(x=80,y=310)
#dadsituation.pack()
dadfonction = Label(frame, text= "Foction du père :" , font='Verdana 14 bold')
dadfonction.place(x=80,y=340)
#dadfonction.pack()
momname = Label(frame, text= "Nom de la mère :" , font='Verdana 14 bold')
momname.place(x=80,y=370)
#momname.pack()
momsituation = Label(frame, text= "Situation matrimoniale :" , font='Verdana 14 bold')
momsituation.place(x=80,y=400)
#momsituation.pack()
momfonction = Label(frame, text= "Foncton de la mère :" , font='Verdana 14 bold')
momfonction.place(x=80,y=430)
#momfonction.pack()

first_name = Entry(frame, width=40 , textvariable = first_name)
first_name.place(x=350 , y=130)	
#first_name.pack(padx=30)
last_name = Entry(frame, width=40 , textvariable = last_name)
last_name.place(x=350 , y=160)
#last_name.pack()	
datenaiss = DateEntry(frame, state="readonly", width=40, date_pattern="dd/mm/yyyy")
datenaiss.place(x=350 , y=190)
#datenaiss.pack()
city = Entry(frame, width=40,textvariable = city)
city.place(x=350 , y=250)
#city.pack()
Gender_mascuslin= ttk.Radiobutton(frame,text='Masculin', value="Masculin").place(x= 350 , y= 215)
Gender_feminin = ttk.Radiobutton(frame,text='Feminin', value="Feminin").place(x= 350 , y= 230)
dadname = Entry(frame, width=40 )
dadname.place(x=350 , y=280)
dadsituation = Entry(frame, width=40 , textvariable = first_name)
dadsituation.place(x=350 , y=310)	
dadfonction = Entry(frame, width=40 , textvariable = last_name)
dadfonction.place(x=350 , y=340)	
momname = Entry(frame, width=40)
momname.place(x=350, y=370)
momsituation = Entry(frame, width=40,textvariable = city)
momsituation.place(x=350, y=400)
momfonction = Entry(frame, width=40,textvariable = city)
momfonction.place(x=350 , y=430)

btn_signup = Button(frame, text = "Enregistrer" ,font='Verdana 10 bold')
btn_signup.place(x=270, y=500)

	
#Radio_button_male = ttk.Radiobutton(winsignup,text='Male', value="Male", variable = var).place(x= 200 , y= 220)
#Radio_button_female = ttk.Radiobutton(winsignup,text='Female', value="Female", variable = var).place(x= 200 , y= 238)

#frame.pack(expand=YES)
#obj=formMysql(root)
frame.mainloop()
